name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install nml

    - name: Set execute permission for findversion.sh
      run: chmod +x ./findversion.sh

    - name: Build NewGRF
      run: make all

    - name: Set variables
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD 2>/dev/null)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 544b0202-Korean-Bus-Set-${{ steps.vars.outputs.sha_short }}  # Name with sha short hash
        path: ./generated/544b0202-Korean-Bus-Set-*.tar
